matrix:
    include:
        - language: java
          jdk: oraclejdk8

        - language: python
          python: "3.6"
          script: pytest

        - language: cpp
          addons:
            apt:
              sources:
                - ubuntu-toolchain-r-test
              packages:
                - g++-7
          env:
            - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
          script: make day3

        - language: d
          d: "dmd"
          script: make day4

        - language: go
          go: "1.10.x"
          install: go get -v ./...
          script: go test -v ./...

        - language: ruby
          rvm: "2.6.0"
          script: make day6

before_install:
    - eval "${MATRIX_EVAL}"
