matrix:
    include:
        - language: java
          jdk: oraclejdk8
          before_install: cd day1
          script: mvn test

        - language: python
          python: "3.6"
          before_install: cd day2
          script: pytest

        - language: cpp
          addons:
            apt:
              sources:
                - ubuntu-toolchain-r-test
              packages:
                - g++-7
          env:
            - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
          before_install: |
            cd day3
            eval "${MATRIX_EVAL}"
          script: make

        - language: d
          d: "dmd"
          before_install: cd day4
          script: make

        - language: go
          go: "1.10.x"
          before_install: cd day5
          install: go get -v ./...
          script: go test -v ./...

        - language: ruby
          rvm: "2.6.0"
          before_install: cd day6
          script: make

        - language: node_js
          node_js: "10"
          before_install: |
            cd day7
            npm ci
          script: npm test

        - language: scala
          scala: "2.12.7"
          before_install: cd day8
          script: sbt ++$TRAVIS_SCALA_VERSION test
