matrix:
    include:
        - language: java
          jdk: oraclejdk8

        - language: python
          python: "3.6"
          script: pytest

        - language: cpp
          addons:
            apt:
              sources:
                - ubuntu-toolchain-r-test
              packages:
                - g++-7
          env:
            - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
          script: make

before_install:
    - eval "${MATRIX_EVAL}"
