require "rake/testtask"

task default: %w[test run]

Rake::TestTask.new :test do |t|
  t.libs << "tests"
  t.test_files = FileList['tests/test*.rb']
  t.verbose = true
end

task :run do
  ruby "main.rb 10000 input.txt output.txt"
  sh "cat output.txt"
  printf "\n"
end
